### ISSUE TITLE
some of the snippet comments are quite noisy

### ISSUE THREAD

**Issue by bentorkington** [VirtualWhirlwind/vscode-povray2#15]
Looking to have a discussion on just how useful the comments provided by the snippets are, e.g. these <x, y, z> / <red, green, blue> comments:
```povray
light_source {
  <10, 10, -10> // <x, y, z>
  color <1.0, 1.0,  1.0> // <red, green, blue>
  spotlight radius 5 falloff 10 tightness 0
  point_at <0, 0, 0>
}
```
Since the order and use of x, y, z and r, g, b are quite readily understood, I would say these represent elementary Povray knowledge that probably won't help many people. Povray's grammar tends to use keywords as seen above with `radius`, `falloff` and `tightness` where a parameter would be less obvious.

Personally, I use comments sparingly and prefer them to stand out when I do use them. Having the code littered with these reminders tends to distract from that, and I spend a lot of time deleting them.

It might be better for the snippets' placeholders to have these mnemonics instead of default values that are unlikely to be useful anyway. Instead of:

```
            "\tcolor <${5:1.0}, ${6:1.0},  ${7:1.0}> // <red, green, blue>",
```

I propose:

```
            "\tcolor <${5:red}, ${6:green},  ${7:blue}>",
```

What does everyone think? I suppose the question is whether the goal of the extension is to help people learn Povray, or help people who are already familiar with the syntax and just want text editor smarts for it.

**Comment by kennebel** [comment]
I find myself deleting a lot of them. I'll look in to an option for cleaning this up.

**Comment by kennebel** [comment]
I love the suggestions. I had one comment of an RGB section you handled differently than the others. I liked the new pattern so suggested just following that.

Thanks for the great idea! More compact and functional, less extraneous text.

**Comment by bentorkington** [comment]
Looks like I just forgot to do that bit. I'm heading away for the weekend (birthday today 🥳) so I'll try and pick it up again later

**Comment by kennebel** [comment]
Sounds good, have a good weekend. Sorry for sitting on these PR's for almost two weeks.

I figured you just overlooked that extra line. This is why I love PR's! Collaboration!

I say go for it for all of the color lines when you get back (noticed there are others too).
