### ISSUE TITLE
An .editorconfig would help with code style

### ISSUE THREAD

**Issue by bentorkington** [VirtualWhirlwind/vscode-povray2#16]
The codebase has a mixture of formatting, sometimes four space tabs, sometimes two. On shared projects, it can help to set a `.editorconfig`file in the root which specifies several standard formatting choices, which is well supported by many editors in addition to VSCode.

This also helps prevent whitespace commits whenever contributors change parts of the code, applying (perhaps inadvertently) their own tab preferences.

**Comment by kennebel** [comment]
I put the .editorconfig in, and it tweaked the main file. I'll touch the rest of the files over time and get them all in line. Thanks for the suggestion! I'm a huge fan of system enforced consistency.
